/**
 * 공통 타입 정의
 * 애플리케이션 전체에서 사용되는 타입들을 정의합니다.
 */

// ============================================
// YouTube 관련 타입
// ============================================

/** YouTube 영상 정보 */
export interface VideoInfo {
    id: string;
    title: string;
    author: string;
    authorUrl?: string;
    thumbnailUrl: string;
    thumbnailUrlFallback?: string;
}

/** 자막 세그먼트 */
export interface TranscriptSegment {
    start: number;
    duration: number;
    text: string;
}

/** 자막 데이터 */
export interface TranscriptData {
    videoId: string;
    language: string;
    languageName?: string;
    segments: TranscriptSegment[];
    fullText: string;
    segmentCount?: number;
    isAutoGenerated?: boolean;
    error?: string;
}

// ============================================
// 퀴즈 관련 타입
// ============================================

/** 퀴즈 유형 */
export type QuizType = 'ox' | 'choice' | 'short';

/** 퀴즈 문제 */
export interface Quiz {
    type: QuizType;
    question: string;
    answer: boolean | number | string;
    explanation: string;
    options?: string[]; // 선택형 문제의 보기
}

/** 퀴즈 생성 결과 */
export interface QuizResult {
    quizzes: Quiz[];
}

// ============================================
// 연관 내용 관련 타입
// ============================================

/** 연관 키워드 */
export interface RelatedKeyword {
    term: string;
    description: string;
}

/** 연관 내용 생성 결과 */
export interface RelatedResult {
    keywords: RelatedKeyword[];
}

// ============================================
// 채팅 관련 타입
// ============================================

/** 채팅 메시지 역할 */
export type ChatRole = 'user' | 'assistant' | 'system';

/** 채팅 메시지 */
export interface ChatMessage {
    role: ChatRole;
    content: string;
}

/** 채팅 세션 */
export interface ChatSession {
    id: string;
    title: string;
    messages: ChatMessage[];
    createdAt?: number;
}

// ============================================
// 설정 관련 타입
// ============================================

/** 사용자 설정 */
export interface UserSettings {
    apiKey: string;
    model: string;
    maxTokens: number;
    temperature: number;
}

// ============================================
// 히스토리 관련 타입
// ============================================

/** 학습 히스토리 항목 */
export interface HistoryItem {
    videoId: string;
    title?: string;
    thumbnailUrl?: string;
    transcript?: string;
    summary?: string;
    quizzes?: Quiz[];
    thinkMore?: string;
    related?: RelatedKeyword[];
    createdAt?: number;
    updatedAt?: number;
}

// ============================================
// OpenRouter API 관련 타입
// ============================================

/** OpenRouter API 호출 옵션 */
export interface OpenRouterOptions {
    apiKey: string;
    model?: string;
    messages: ChatMessage[];
    maxTokens?: number;
    temperature?: number;
    stream?: boolean;
    onStream?: (chunk: string, fullContent: string) => void;
}

/** 스트림 콜백 함수 */
export type StreamCallback = (chunk: string, fullContent: string) => void;

// ============================================
// 컴포넌트 Props 타입
// ============================================

/** 버튼 변형 */
export type ButtonVariant = 'primary' | 'secondary' | 'accent' | 'ghost' | 'danger';

/** 버튼 크기 */
export type ButtonSize = 'sm' | 'md' | 'lg';

/** 모달 크기 */
export type ModalSize = 'sm' | 'md' | 'lg';
